configuration:
  name: data_process
  workplace: ./Data/
  encoding: utf-8

  train_data_path: ./Data/ecg_train_data.json
  test_data_path: ./Data/ecg_test_data.xlsx

  train_Post_file: ./Data/train_Post.tsv
  train_Response_file: ./Data/train_Response.tsv
  train_Choice_file: ./Data/train_Choice.tsv
  train_Emo_file: ./Data/train_Emo.tsv

  dev_Post_file: ./Data/dev_Post.tsv
  dev_Response_file: ./Data/dev_Response.tsv
  dev_Choice_file: ./Data/dev_Choice.tsv
  dev_Emo_file: ./Data/dev_Emo.tsv

  emo_words_file_path: ./Data/Emotion_words/
  Emotion_Dict_file: ./Data/Emotion_Dict.json
